from typing import Dict, Any

TREATMENTS: Dict[str, Dict[str, Any]] = {
    "Pepper,_bell___Bacterial_spot": {
        "display_name": "Bell Pepper — Bacterial Spot",
        "severity": "High",
        "description": "Bacterial spot is caused by Xanthomonas campestris pv. vesicatoria. It spreads rapidly in warm, wet conditions and can devastate pepper crops, causing significant yield loss through defoliation and fruit spotting.",
        "symptoms": [
            "Small, water-soaked spots on leaves that turn brown with yellow halos",
            "Raised, scabby lesions on fruit surface",
            "Premature defoliation in severe cases",
            "Dark, greasy-looking spots on undersides of leaves",
            "Stem lesions causing plant wilting",
        ],
        "treatment": "Remove and destroy infected plant material immediately. Apply copper-based bactericides every 7–10 days during wet weather. Avoid overhead irrigation and work in the field when plants are wet.",
        "organic_treatment": "Spray copper hydroxide (Kocide 3000) at 1.25 kg/ha. Apply Bacillus subtilis biofungicide weekly. Use neem oil solution (2%) as supplemental spray. Improve air circulation by pruning.",
        "chemical_treatment": "Apply copper octanoate (Cueva) or copper hydroxide at label rates. Tank-mix with mancozeb for enhanced efficacy. Rotate with acibenzolar-S-methyl (Actigard) to induce systemic resistance.",
        "prevention": "Use certified disease-free seeds. Apply hot water seed treatment (52°C for 30 min). Practice 2–3 year crop rotation. Select resistant varieties. Avoid overhead irrigation; use drip systems.",
        "recovery_days": 21,
        "is_healthy": False,
    },
    "Pepper,_bell___healthy": {
        "display_name": "Bell Pepper — Healthy",
        "severity": "Low",
        "description": "Your bell pepper plant appears healthy with no signs of disease. Continue current management practices to maintain plant health and maximise yield.",
        "symptoms": [
            "Deep green, glossy foliage",
            "Sturdy stems with no lesions",
            "Normal flower and fruit development",
        ],
        "treatment": "No treatment required. Maintain regular watering schedule and balanced fertilisation.",
        "organic_treatment": "Continue compost applications and foliar seaweed sprays to strengthen plant immunity.",
        "chemical_treatment": "No chemical intervention needed. Maintain preventive copper spray schedule if bacterial spot is common in your area.",
        "prevention": "Maintain adequate plant spacing for airflow. Monitor weekly for early signs of disease. Keep irrigation water off foliage.",
        "recovery_days": 0,
        "is_healthy": True,
    },
    "Potato___Early_blight": {
        "display_name": "Potato — Early Blight",
        "severity": "Medium",
        "description": "Early blight is caused by the fungus Alternaria solani. It typically affects older leaves first and can cause significant defoliation if uncontrolled, reducing tuber yield by 20–30% in severe cases.",
        "symptoms": [
            "Dark brown to black circular lesions with concentric rings (target-board pattern)",
            "Yellow halo surrounding lesions",
            "Lower, older leaves affected first",
            "Lesions on stems appearing as dark, sunken areas",
            "Premature yellowing and dropping of leaves",
        ],
        "treatment": "Apply fungicides at first sign of symptoms. Remove severely infected lower leaves. Maintain adequate soil nitrogen as stressed plants are more susceptible. Ensure consistent soil moisture.",
        "organic_treatment": "Apply copper-based fungicide (copper sulfate 1%) weekly. Spray Bacillus subtilis (Serenade) every 7 days. Use biostimulants containing silicon to strengthen cell walls. Apply compost tea foliar sprays.",
        "chemical_treatment": "Apply azoxystrobin (Quadris), chlorothalonil, or mancozeb at label rates. Begin applications at tuber initiation or when disease first appears. Rotate fungicide classes to prevent resistance.",
        "prevention": "Plant certified disease-free seed potatoes. Maintain balanced nitrogen fertilisation. Use furrow or drip irrigation. Remove crop debris after harvest. Practice 3-year crop rotation with non-Solanaceous crops.",
        "recovery_days": 14,
        "is_healthy": False,
    },
    "Potato___Late_blight": {
        "display_name": "Potato — Late Blight",
        "severity": "Critical",
        "description": "Late blight, caused by Phytophthora infestans, is the most destructive potato disease globally — responsible for the Irish Famine of the 1840s. It can destroy an entire crop within days under cool, wet conditions.",
        "symptoms": [
            "Water-soaked, pale green lesions on leaf margins that rapidly turn dark brown",
            "White, downy sporulation on underside of leaves in humid conditions",
            "Dark brown, firm rot on tubers extending from the surface",
            "Rapid collapse and death of entire plant canopy (blight)",
            "Distinct musty odour from infected tissue",
        ],
        "treatment": "URGENT: Act immediately. Apply systemic fungicide within 24 hours of detection. Remove and bag all infected plant material — do not compost. Destroy infected tubers. Alert neighbouring farmers as spores spread via wind up to 10 km.",
        "organic_treatment": "Apply copper sulfate (Bordeaux mixture) immediately. Use phosphorous acid sprays to suppress sporangia. Remove and bury infected tissue. Avoid any overhead irrigation.",
        "chemical_treatment": "Apply cymoxanil + mancozeb (Curzate) or metalaxyl-M + mancozeb (Ridomil Gold) immediately. Follow with dimethomorph (Acrobat) applications every 5–7 days. Rotate between fungicide classes.",
        "prevention": "Monitor daily using Late Blight DSS (decision support systems). Plant resistant varieties (Sarpo Mira, Cara). Apply preventive copper sprays from crop emergence. Ensure excellent field drainage. Destroy volunteer potato plants.",
        "recovery_days": 35,
        "is_healthy": False,
    },
    "Potato___healthy": {
        "display_name": "Potato — Healthy",
        "severity": "Low",
        "description": "Your potato plant appears healthy. Maintain current practices and monitor regularly given potato's susceptibility to blight under wet conditions.",
        "symptoms": [
            "Dark green, vigorous foliage",
            "No lesions or water-soaked areas",
            "Normal stem development",
        ],
        "treatment": "No treatment required. Continue regular scouting every 3–4 days during wet weather.",
        "organic_treatment": "Apply preventive copper sprays as insurance during high-humidity periods. Use seaweed extracts to boost plant immunity.",
        "chemical_treatment": "Consider preventive mancozeb applications if late blight risk is high in your region (check local forecasting services).",
        "prevention": "Monitor weather forecasts for blight-conducive conditions (Smith Periods). Maintain good airflow between plants. Harvest tubers in dry conditions.",
        "recovery_days": 0,
        "is_healthy": True,
    },
    "Tomato___Bacterial_spot": {
        "display_name": "Tomato — Bacterial Spot",
        "severity": "High",
        "description": "Caused by Xanthomonas species, bacterial spot is a major tomato disease in warm, humid climates. Losses of 10–50% are common in unprotected crops during rainy seasons.",
        "symptoms": [
            "Small, dark brown spots with yellow halos on leaves",
            "Raised, scabby, water-soaked lesions on fruit",
            "Spots coalesce to form large necrotic areas",
            "Defoliation exposing fruit to sunscald",
            "Dark streaks on stems",
        ],
        "treatment": "Apply copper bactericides immediately. Remove heavily infected leaves. Switch to drip irrigation. Apply at 7-day intervals during rainy weather, 14-day during dry.",
        "organic_treatment": "Copper hydroxide sprays weekly. Bacillus subtilis (Serenade) applications. Neem oil at 2% concentration. Avoid working in wet crops to limit spread.",
        "chemical_treatment": "Copper hydroxide + mancozeb tank mix. Acibenzolar-S-methyl (Actigard) for SAR induction at 0.75 oz/100 gal every 14 days. Fixed copper at label rates.",
        "prevention": "Use resistant varieties (Tasti-Lee, BHN-602). Seed treatment with hot water (52°C/25 min) or sodium hypochlorite. Stake plants for airflow. Practice 2-year rotation.",
        "recovery_days": 21,
        "is_healthy": False,
    },
    "Tomato___Early_blight": {
        "display_name": "Tomato — Early Blight",
        "severity": "Medium",
        "description": "Caused by Alternaria solani, early blight is one of the most common tomato foliar diseases. It progresses upward from older leaves and is favoured by warm, wet weather alternating with dry periods.",
        "symptoms": [
            "Dark brown target-board lesions with concentric rings",
            "Yellowing (chlorosis) surrounding lesions",
            "Lesions on stems causing collar rot in seedlings",
            "Dark, leathery lesions at the stem end of fruit",
            "Progressive defoliation from base upward",
        ],
        "treatment": "Remove and destroy infected leaves. Apply fungicide at 7-day intervals. Ensure adequate potassium and calcium nutrition. Stake plants to improve airflow.",
        "organic_treatment": "Spray copper sulfate weekly. Apply Trichoderma harzianum to soil. Use compost tea foliar spray. Mulch soil to reduce spore splash-up.",
        "chemical_treatment": "Chlorothalonil (Bravo), azoxystrobin (Quadris), or boscalid + pyraclostrobin (Pristine). Apply at first symptom appearance. Rotate fungicide groups.",
        "prevention": "Remove crop debris thoroughly. Use mulch to reduce soilborne inoculum. Maintain proper plant nutrition. Choose resistant varieties. Stake or cage plants for airflow.",
        "recovery_days": 14,
        "is_healthy": False,
    },
    "Tomato___Late_blight": {
        "display_name": "Tomato — Late Blight",
        "severity": "Critical",
        "description": "Phytophthora infestans causes late blight in tomatoes as well as potatoes. Under cool, wet conditions the entire plant can collapse within a week. Infected fruit is completely unmarketable.",
        "symptoms": [
            "Large, irregular, water-soaked lesions rapidly turning brown-black",
            "White sporulation on leaf undersides under humid conditions",
            "Dark brown to black lesions on stems causing collapse",
            "Firm, dark brown rot on green or ripe fruit",
            "Rapid vinewide collapse in severe outbreaks",
        ],
        "treatment": "URGENT: Apply systemic fungicide within 24 hours. Remove and destroy all infected material. Do not compost. Notify extension service if outbreak is severe.",
        "organic_treatment": "Bordeaux mixture (copper sulfate + lime) immediately. Phosphorous acid sprays. Biofungicide containing Bacillus amyloliquefaciens as supplemental spray.",
        "chemical_treatment": "Metalaxyl-M + mancozeb (Ridomil Gold MZ). Cymoxanil (Curzate). Fluopicolide + propamocarb (Infinito). Apply on 5–7 day schedule during wet weather.",
        "prevention": "Monitor late blight forecasting tools daily. Use resistant varieties (Mountain Merit, Defiant PhR). Apply preventive copper sprays from transplanting. Ensure excellent drainage.",
        "recovery_days": 35,
        "is_healthy": False,
    },
    "Tomato___Leaf_Mold": {
        "display_name": "Tomato — Leaf Mold",
        "severity": "Medium",
        "description": "Caused by Passalora fulva (formerly Fulvia fulva), leaf mold is primarily a problem in greenhouse tomatoes and in high-humidity field conditions above 85% RH. It reduces photosynthesis and fruit quality.",
        "symptoms": [
            "Pale green to yellow patches on upper leaf surface",
            "Olive-green to grey velvety mold growth on lower leaf surface",
            "Older leaves affected first, progressing upward",
            "Severe infection causes leaf curling and drop",
            "Fruit rarely infected but flower drop can occur",
        ],
        "treatment": "Reduce humidity immediately by improving ventilation. Remove heavily infected leaves. Apply fungicide. Space plants adequately. Avoid wetting foliage.",
        "organic_treatment": "Spray with potassium bicarbonate solution. Apply sulfur dust or wettable sulfur in dry conditions. Use Bacillus subtilis biofungicide weekly.",
        "chemical_treatment": "Chlorothalonil, mancozeb, or copper-based fungicides. In greenhouses: difenoconazole (Score) or cyprodinil + fludioxonil (Switch). Rotate between FRAC groups.",
        "prevention": "Maintain greenhouse RH below 85%. Use resistant varieties (Daniela, Sabrina). Prune lower leaves. Ensure adequate plant spacing. Ventilate during evening hours.",
        "recovery_days": 14,
        "is_healthy": False,
    },
    "Tomato___Septoria_leaf_spot": {
        "display_name": "Tomato — Septoria Leaf Spot",
        "severity": "Medium",
        "description": "Septoria lycopersici causes one of the most common tomato diseases in eastern North America. It spreads rapidly in wet weather and can cause severe defoliation, weakening plants and exposing fruit to sunscald.",
        "symptoms": [
            "Numerous small circular spots with dark brown borders and grey-white centres",
            "Tiny black pycnidia (fruiting bodies) visible in spot centres",
            "Lower leaves affected first, progressing upward",
            "Severe defoliation in wet conditions",
            "Rarely affects fruit directly",
        ],
        "treatment": "Apply fungicide immediately. Remove infected lower leaves. Mulch around plants. Stake plants for improved airflow. Avoid overhead watering.",
        "organic_treatment": "Copper-based fungicides weekly. Bacillus subtilis (Serenade) at 7-day intervals. Compost tea sprays. Remove and bag infected leaves.",
        "chemical_treatment": "Chlorothalonil (Bravo), mancozeb, or azoxystrobin. Apply on 7–10 day schedule. Alternating strobilurin with protectant fungicides reduces resistance risk.",
        "prevention": "Remove crop debris and volunteer tomatoes. Use mulch to prevent spore splashing. Practice 2-year rotation. Select resistant varieties. Stake plants well.",
        "recovery_days": 14,
        "is_healthy": False,
    },
    "Tomato___Spider_mites Two-spotted_spider_mite": {
        "display_name": "Tomato — Two-Spotted Spider Mite",
        "severity": "High",
        "description": "Tetranychus urticae is a major tomato pest, not a disease. It thrives in hot, dry conditions and can build to damaging populations rapidly. Heavy infestations cause plant death. Pesticide resistance is common.",
        "symptoms": [
            "Fine, stippled bronzing of upper leaf surface",
            "Fine silk webbing on leaf undersides and between leaves",
            "Tiny moving dots (mites) visible under 10× hand lens",
            "Yellowing, bronzing, and death of leaves in severe infestations",
            "Stunted growth and reduced fruit set",
        ],
        "treatment": "Spray undersides of leaves thoroughly with miticide. Apply in early morning or evening. Repeat at 5–7 day intervals. Knock mite populations down quickly — they double every 5 days in hot weather.",
        "organic_treatment": "Spray with insecticidal soap or neem oil (2%), targeting leaf undersides. Release predatory mites (Phytoseiulus persimilis, Neoseiulus californicus). Increase plant humidity. Blast plants with water spray.",
        "chemical_treatment": "Abamectin (Agrimek), spiromesifen (Oberon), or bifenazate (Acramite). CRITICAL: Rotate miticide classes every application — resistance develops rapidly. Do not use pyrethroids (these kill beneficial insects and cause mite flares).",
        "prevention": "Monitor with 10× hand lens weekly. Maintain adequate soil moisture. Avoid dusty conditions. Avoid broad-spectrum pesticides that eliminate natural enemies. Introduce predatory mites preventively in greenhouses.",
        "recovery_days": 10,
        "is_healthy": False,
    },
    "Tomato___Target_Spot": {
        "display_name": "Tomato — Target Spot",
        "severity": "Medium",
        "description": "Caused by Corynespora cassiicola, target spot has become increasingly important in tomato production worldwide. It affects leaves, stems, and fruit, causing significant quality and yield losses.",
        "symptoms": [
            "Brown concentric ring lesions resembling a target or bulls-eye",
            "Yellow halo surrounding lesions",
            "Lesions on green and ripe fruit — superficial to deep",
            "Stem lesions causing dark, sunken cankers",
            "Defoliation in severe cases",
        ],
        "treatment": "Apply fungicide at first symptom appearance. Remove infected leaves. Improve airflow by pruning and staking. Avoid overhead irrigation.",
        "organic_treatment": "Copper-based fungicides at weekly intervals. Bacillus subtilis biofungicides. Silicon-based products to strengthen leaf tissue.",
        "chemical_treatment": "Azoxystrobin (Quadris), difenoconazole, or boscalid + pyraclostrobin (Pristine). Apply on 7–10 day intervals. Rotate FRAC groups to manage resistance.",
        "prevention": "Use resistant varieties where available. Ensure good airflow. Practice sanitation — remove crop debris. 2-year crop rotation.",
        "recovery_days": 14,
        "is_healthy": False,
    },
    "Tomato___Tomato_Yellow_Leaf_Curl_Virus": {
        "display_name": "Tomato — Yellow Leaf Curl Virus",
        "severity": "Critical",
        "description": "Tomato Yellow Leaf Curl Virus (TYLCV) is transmitted by whiteflies (Bemisia tabaci) and is one of the most devastating tomato diseases in tropical and subtropical regions. There is no cure once a plant is infected.",
        "symptoms": [
            "Upward curling and cupping of young leaves",
            "Severe yellowing (chlorosis) of leaf margins",
            "Stunted, bushy plant growth",
            "Flower drop and drastically reduced fruit set",
            "Small, pale, deformed fruit on plants infected early",
        ],
        "treatment": "REMOVE and destroy infected plants immediately to prevent whitefly spread to healthy plants. There is no cure. Focus entirely on whitefly vector control and protecting remaining healthy plants.",
        "organic_treatment": "Remove infected plants promptly. Use reflective silver mulch to deter whiteflies. Apply insecticidal soap or neem oil to remaining plants. Install yellow sticky traps for monitoring. Use row covers on transplants.",
        "chemical_treatment": "Control whitefly vector: imidacloprid soil drench at transplanting (systemic protection), followed by spirotetramat (Movento) or flupyradifurone (Sivanto) foliar sprays. Rotate insecticide classes. No direct antiviral treatment exists.",
        "prevention": "Plant TYLCV-resistant varieties (TY-1 gene: Tyking, Shanty, Hazera varieties). Use insect-proof nets in nurseries. Apply imidacloprid at transplanting. Scout weekly for whiteflies. Remove weeds that host whiteflies.",
        "recovery_days": 999,
        "is_healthy": False,
    },
    "Tomato___Tomato_mosaic_virus": {
        "display_name": "Tomato — Mosaic Virus",
        "severity": "High",
        "description": "Tomato Mosaic Virus (ToMV) is mechanically transmitted by contact and is highly persistent in plant debris and on tools. It causes significant yield losses through stunting and fruit deformation. No cure exists.",
        "symptoms": [
            "Mosaic pattern of light and dark green areas on leaves",
            "Leaf distortion, puckering, and fern-leaf symptoms",
            "Stunted plant growth",
            "Bronze or brown discolouration of fruit interior",
            "Deformed, mottled, or streaked fruit",
        ],
        "treatment": "Remove and destroy infected plants. Disinfect all tools with 10% bleach or 70% alcohol between plants. Wash hands thoroughly. There is no chemical cure for viral infections.",
        "organic_treatment": "Remove infected plants. Sterilise tools with sodium hypochlorite (10%). Use skimmed milk spray (10%) on tools and hands — casein proteins inhibit virus transmission. Control aphids and thrips as secondary vectors.",
        "chemical_treatment": "No antiviral chemicals are effective. Focus on vector control: imidacloprid for thrips/aphids. Induce systemic resistance with acibenzolar-S-methyl (Actigard) as partial protection.",
        "prevention": "Use ToMV-resistant varieties (Tm-2² gene). Sanitise tools between plants. Do not smoke near tomato plants (tobacco contains TMV). Pasteurise growing media. Use virus-free certified seed.",
        "recovery_days": 999,
        "is_healthy": False,
    },
    "Tomato___healthy": {
        "display_name": "Tomato — Healthy",
        "severity": "Low",
        "description": "Your tomato plant appears healthy and vigorous. Continue current management practices. Regular scouting is essential as tomato is susceptible to many diseases.",
        "symptoms": [
            "Deep green, uncurled foliage",
            "No lesions, spots, or mold visible",
            "Normal stem and root development",
            "Active flowering and fruit set",
        ],
        "treatment": "No treatment required. Scout every 3–4 days for early disease signs.",
        "organic_treatment": "Preventive neem oil spray monthly. Compost tea foliar spray bi-weekly. Maintain good soil biology with compost additions.",
        "chemical_treatment": "No chemical intervention needed. Consider preventive copper + mancozeb applications before wet weather periods.",
        "prevention": "Stake or cage all plants. Use drip irrigation. Remove suckers to improve airflow. Mulch soil surface. Monitor for whiteflies, aphids, and mites weekly.",
        "recovery_days": 0,
        "is_healthy": True,
    },
}


def get_treatment_info(disease_key: str) -> Dict[str, Any]:
    if disease_key in TREATMENTS:
        return TREATMENTS[disease_key]

    is_healthy = "healthy" in disease_key.lower()
    display_name = disease_key.replace("___", " — ").replace("_", " ")

    if is_healthy:
        return {
            "display_name": display_name,
            "severity": "Low",
            "description": f"Your {display_name.split(' — ')[0]} plant appears healthy with no visible signs of disease.",
            "symptoms": ["Healthy foliage", "Vigorous stems"],
            "treatment": "No treatment required. Maintain regular watering and fertilization.",
            "organic_treatment": "Continue organic soil improvement and crop monitoring.",
            "chemical_treatment": "No chemical intervention required.",
            "prevention": "Ensure good spacing, clean tools, and check plants weekly.",
            "recovery_days": 0,
            "is_healthy": True
        }
    else:
        return {
            "display_name": display_name,
            "severity": "Medium",
            "description": f"Detected {display_name} on your plant. Monitor the crop closely and take preventive action.",
            "symptoms": ["Leaf spots or discoloration", "Early signs of plant stress"],
            "treatment": "Prune and dispose of infected leaves. Avoid overhead watering.",
            "organic_treatment": "Apply organic neem oil (2%) or copper-based sprays preventatively.",
            "chemical_treatment": "Apply broad-spectrum fungicides according to local guidelines.",
            "prevention": "Practice crop rotation, remove weeds, and select disease-free seeds.",
            "recovery_days": 14,
            "is_healthy": False
        }