import { useState } from 'react'

const TABS = [
  { id: 'overview',  label: 'Overview' },
  { id: 'organic',   label: 'Organic' },
  { id: 'chemical',  label: 'Chemical' },
  { id: 'prevention',label: 'Prevention' },
]

export default function TreatmentPanel({ result }) {
  const [activeTab, setActiveTab] = useState('overview')

  if (!result || result.disease === 'Unknown') return null

  const handleShare = async () => {
    const text = `CropDoctor Report
Disease: ${result.display_name}
Confidence: ${(result.confidence * 100).toFixed(1)}%
Severity: ${result.severity}

Treatment: ${result.treatment}

Prevention: ${result.prevention}

Generated by CropDoctor AI`

    if (navigator.share) {
      try {
        await navigator.share({ title: 'CropDoctor Report', text })
        return
      } catch (_) {}
    }
    await navigator.clipboard.writeText(text)
    alert('Report copied to clipboard!')
  }

  return (
    <div className="card">
      <div className="section-title">Treatment Guide</div>

      <div className="tab-row">
        {TABS.map((t) => (
          <button
            key={t.id}
            className={`tab-pill ${activeTab === t.id ? 'active' : ''}`}
            onClick={() => setActiveTab(t.id)}
          >
            {t.label}
          </button>
        ))}
      </div>

      {activeTab === 'overview' && (
        <div>
          {result.symptoms?.length > 0 && (
            <>
              <div className="section-title" style={{ marginTop: 0 }}>Symptoms</div>
              <ul className="symptoms-list">
                {result.symptoms.map((s, i) => <li key={i}>{s}</li>)}
              </ul>
              <div style={{ marginTop: 16 }}>
                <div className="section-title">Primary Treatment</div>
                <p className="treatment-text">{result.treatment}</p>
              </div>
            </>
          )}
          {!result.is_healthy && result.recovery_days > 0 && result.recovery_days < 999 && (
            <div style={{ marginTop: 20 }}>
              <div className="section-title">Recovery Timeline</div>
              <div className="recovery-timeline">
                <div className="timeline-dot" />
                <div className="timeline-line" />
                <div className="timeline-end" />
              </div>
              <div className="timeline-labels">
                <span>Today</span>
                <span>~{result.recovery_days} days</span>
              </div>
            </div>
          )}
          {result.recovery_days >= 999 && (
            <div className="error-banner" style={{ marginTop: 16 }}>
              ⚠️ This disease has no cure. Remove infected plants and prevent spread.
            </div>
          )}
        </div>
      )}

      {activeTab === 'organic' && (
        <p className="treatment-text">{result.organic_treatment}</p>
      )}

      {activeTab === 'chemical' && (
        <div>
          <p className="treatment-text">{result.chemical_treatment}</p>
          <div className="error-banner" style={{ marginTop: 12 }}>
            ⚠️ Always read labels and follow safety guidelines. Wear PPE. Observe pre-harvest intervals.
          </div>
        </div>
      )}

      {activeTab === 'prevention' && (
        <p className="treatment-text">{result.prevention}</p>
      )}

      <button className="share-btn" onClick={handleShare}>
        📤 Share Report
      </button>
    </div>
  )
}